### ISSUE TITLE
Add tests about creating multisampled textures with RENDER_ATTACHMENT usage

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/cts#1521]
See https://github.com/gpuweb/gpuweb/pull/2786 for more details.

issue: #1508

**Comment by kainino0x** [comment]
FYI when you file a CTSissue for a spec change, you can go to the spec change and make sure it's not marked as "Needs CTS issue". That way we won't have to figure out that it's already been filed :)

I just changed https://github.com/gpuweb/gpuweb/pull/2786 from "Needs CTS Issue" to "Specification Done".

(FYI I might change the tracking system slightly at some point, since it's a little redundant right now - but it should be similar, either a project status or an actual label)
