### ISSUE TITLE
wgsl: Add idiomatic support for f16 values

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#1812]
What is the proper way to pull in a dependency to the CTS?

Specifically I am looking at implementing testing of `quantizeToF16`, so would like to have `Float16Array` like we use `Float32Array` to avoid having to hand implement things. But unfortunately it seems like it hasn't been implemented in JS/TS, and won't likely be https://esdiscuss.org/topic/float16array.

There does appear to be a well supported package for this https://www.npmjs.com/package/@petamoriken/float16
This package is MIT licensed, so I think would be compatible with the CTS's BSD 3-clause license.

Talking with Kai, there is a build version of this package, https://unpkg.com/browse/@petamoriken/float16@3.6.6/browser/float16.mjs, that could be placed in a third_party or external directory instead of bringing in a whole package manager dependency.

I am open to other solutions to this problem, I just honestly don't know where to start.

**Comment by zoddicus** [comment]
I have investigated using the f16 functions from the API side of the CTS, but they currently don't support denorms/subnormals, they have flush-to-zero behaviour. For WGSL handling subnormals is needed, and the existing FTZ behaviour is used by existing tests, so using that code would involve having a switch for FTZ/no-FTZ in addition to needing to implement the details of handling subnormals.

**Comment by zoddicus** [comment]
@tidoust, @kainino0x suggested asking you for advice on this.

In addition to the single function I am trying to test right now, there is going to be an entire suite of f16 based math that needs to be tested in the future, which is why I would prefer to have a more idiomatic approach, like `Float16Array`, instead of just having a one off hand written `hexTof16` function here.

**Comment by kainino0x** [comment]
@tidoust Specifically was hoping you might know the policies about using third party dependencies in W3C test code. We already have dependencies for building this project, but this would be used by the tests themselves. The easiest for us would be to put a copy of the dependency in our source tree, so hoping that we can do that by simply pairing it with a LICENSE file.

**Comment by kainino0x** [comment]
If pulling in a dependency isn't easy we can definitely reimplement Float16Array on top of the work we have so fare.

**Comment by tidoust** [comment]
W3C Test Suites are distributed under [two licenses](https://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html): the 3-clause BSD license, and the W3C Test suite license. The latter prevents alteration of the tests and exists to be able to make performance claims against unaltered tests, it should otherwise be compatible with the 3-clause BSD license.

As long as you're confident that you can integrate the code and that the code you integrate is compatible with these licenses (MIT licensed code typically looks fine), I don't see any problem with the approach you suggest to integrate the code and acknowledge the integration.
