### ISSUE TITLE
webgpu:api,operation,buffers,map_oom: only checks for a JS exception

### ISSUE THREAD

**Issue by austinEng** [gpuweb/cts#199]
This test checks for a JS exception, expecting that mapping an enormous range would cause a RangeError due to failure to allocate an ArrayBuffer that large. On some platforms, this allocation actually succeeds, and then the test fails with an OOM error when the implementation attempts to map such a large GPU buffer.

I suggest this test be updated to allow a GPU OOM error if there is no JS exception.

**Comment by kainino0x** [comment]
That allocation can't truly succeed (it's 2^53-1 bytes). Do we delay attempting the allocation on some platforms? Or do we get address space without committed memory?

**Comment by kainino0x** [comment]
Looking more closely, this test is only looking for exceptions/rejections at the exact time when the `ArrayBuffer` is supposed to be returned. Is the problem here that the exception we get is something other than RangeError? (OperationError because the GPUBuffer is invalid?)

I'm thinking the mapReadAsync/mapWriteAsync tests should strictly require OperationError because we expect the GPUBuffer to definitely be invalid. `createBufferMapped` might keep being a RangeError.

Also the mapReadAsync test is trying to mapReadAsync on a MAP_WRITE buffer so it may be triggering a separate error condition. (And createBufferMapped shouldn't require a MAP usage at all.) Whoops.

**Comment by austinEng** [comment]
I'm trying to figure it out now. Maybe it's getting clamped somewhere.

**Comment by austinEng** [comment]
So we do get `RangeError` on `mapRead/WriteAsync`, but we also get an OOM from `createBuffer`. So we need to be checking for both of those ? Mapping may allocate the shmem before we know it's an error buffer due to OOM.

**Comment by kainino0x** [comment]
Yeah, we should definitely expect an async OOM from createBuffer(MAX_SAFE_INTEGER). We should have a helper for creating oom-error-buffers, similar to getErrorBuffer, and use it in a validation test that checks that oom-error-buffers behave the same as validation-error-buffers, i.e. that mapping on them is an OperationError.

I don't think there's any way for us to actually reliably test for OOMs during mapAsync. If a buffer is valid then I think the best we can do is allocate the GPUBuffer, try to run out of CPU memory (by doing many ArrayBuffer allocations), and then mapAsync. But I'm not sure we can practically make that a conformance test.

We should revisit createBufferMapped after we do mappedAtCreation.
