### ISSUE TITLE
Implement RenderPass StoreOp Tests

### ISSUE THREAD

**Issue by bjjones** [gpuweb/cts#225]
Coverage needed for testing render pass store operations

**/api/validation/**
- [ ] Test that when `depthReadOnly` is `true`, `depthStoreOp` must be `store`
- [ ] Test that when `stencilReadOnly` is `true`, `stencilStoreOp` must be `store`

**/api/operation/**
- [ ] Test that a render pass with colorAttachment `storeOp` set to `clear` has correct output for:
    - [ ] All color renderable formats
    - [ ] All color attachments, from 0 to `MAX_COLOR_ATTACHMENTS`
 
- [ ] Test that a render pass with colorAttachment `storeOp` set to `store` has correct output for:
    - [ ] All color renderable formats
    - [ ] All color attachments, from 0 to `MAX_COLOR_ATTACHMENTS`

- [ ] Test that a render pass with `depthStoreOp` set to `clear` has correct output for:
    - [ ] All depth/stencil formats
- [ ] Test that a render pass with `depthStoreOp` set to `store` has correct output for:
    - [ ] All depth/stencil formats
- [ ] Test that a render pass with `stencilStoreOp` set to `clear` has correct output for:
    - [ ] All depth/stencil formats with stencil component.
- [ ] Test that a render pass with `stencilStoreOp` set to `store` has correct output for:
    - [ ] All depth/stencil formats with stencil component.

**/idl/**
- [ ] Test that a color attachment's `storeOp` is `store` by default
- [ ] Test that depth/stencil attachment's `depthStoreOp` is `store` by default
- [ ] Test that depth/stencil attachment's `stencilStoreOp` is `store` by default

**Comment by bjjones** [comment]
It was mentioned I should write a test plan for the tests I was assigned - so here it is. Feel free to edit the initial comment if I'm missing something.

**Comment by Kangz** [comment]
Thanks for putting this up!

For validation I think we might want to validate that if the `depthStoreOp` or `depthReadOnly` is set, then the attachment must have a depth aspect (and such for all depth-stencil formats). Same thing for `stencilStoreOp` and `stencilReadOnly`.

For operation we might want to test rendering of a bunch of values, but maybe it's not part of the storeOp tests, but for general pixel output?

Also we should test all combinations of depth/stencil ops together for all formats since they are two planes of the same texture. IDK if the checks for default values should be in IDL or operation though. @kainino0x, do you have an opinion?

Also maybe this test should test storing to a non-0 miplevel or array layer of textures for each of the tests.

Finally, @austinEng, where do you think the lazy-clearing of "clear" attachment should be tested? Here or in the resource zero init tests?

**Comment by austinEng** [comment]
The resource zero init tests already use `clear` as one of the ways it obtains uninitialized data. For all possible (eventually) usages of a texture, it either creates a texture and then uses it without initializing it; or creates a texture, initializes it, and "deinitializes" with `clear`. I think it would be okay to leave most of this testing in the resource_init tests, but perhaps have some basic testing in the store op tests for completeness.

**Comment by bjjones** [comment]
Moving to https://github.com/gpuweb/cts/pull/227 as discussed.

**Comment by kainino0x** [comment]
> Also we should test all combinations of depth/stencil ops together for all formats since they are two planes of the same texture. IDK if the checks for default values should be in IDL or operation though. @kainino0x, do you have an opinion?

I thought about this too while reviewing the PR. I don't think we should put them in IDL tests, because they'll require quite a bit of stuff around them that would normally only appear in operation tests (you have to do something to check whether the rendering result was actually correct). Operation tests can be parameterized like [storeOp="clear", storeOp="store", storeOp=undefined] which should make it basically trivial to incorporate many default values into existing operation tests.
