### ISSUE TITLE
tests for unpack*unorm and unpack*snorm builtins should not "inherit" accuracy from float division

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#2485]
Spawned by the observation at https://github.com/gpuweb/cts/pull/2483#discussion_r1165606778 

The unpack*unorm and unpack*snorm builtins are defined in terms of infinitely precise divisions by fixed numbers.
Accuracy should be computed with respect to the infinitely precise result.

But the CTS right now is computing accuracy  "inherited from" the division operation, so it's allowing 2.5 ULP.

This may explain some of the mystery from https://github.com/gpuweb/gpuweb/issues/3991 and https://github.com/gpuweb/gpuweb/pull/3992#issuecomment-1481316764 raised by @alan-baker:  Why does unpack2x16snorm  achieve 3ULP but unpack2x16unorm achieve "correctly rounded".

**Comment by zoddicus** [comment]
Looking at the various bugs related to unpack (https://github.com/gpuweb/cts/issues/2777 and https://bugs.chromium.org/p/tint/issues/detail?id=1881)

It appears that various combinations of devices/platforms (Vulkan/SwiftShader, Vulkan/Nvidia, Metal/AMD, possibly others) and specific unpack operations have 3ULP of error in their results instead of the 2.5ULP of error that would be expected using the inherited accuracy, or the 1ULP that 'correctly rounded' should give.

Given the widespread occurrence of devices with these looser error bounds, the spec was weakened to accommodate them.

**Comment by munrocket** [comment]
I tried to come up with fast polyfill based on split function, but unsuccessfully yet. I only come up to idea how to check device rounding mode, float precision and know a way how to make error-free operations. By the way `frexp` give to us correctly rounded mantissa, it is possible to abuse it.

Don’t you think that error in packing can be annoying in practice? You using built-in functions from OGL/DX/Metal or sometime own function? How they can give errors 🫣

**Comment by zoddicus** [comment]
I am not super familiar with the details of the actual implementation in Tint, looking at initial issue, it looks like Metal is spec'd to have some error in the conversion builtins being used...

@alan-baker @dneto0 can you comment on this, since you were involved in the analysis on the Tint and spec side?

**Comment by munrocket** [comment]
Metal backend have good precision on devices. Maybe special packing polyfill in terms of MSL is needed in Tint/Naga.
