### ISSUE TITLE
wgsl: f32 validation tests for `reflect`

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2730]
Need coverage that when result or intermediaries go OOB, it is rejected for const-eval (shader creation error) and override (pipeline creation error).

**Comment by dneto0** [comment]
Inherited from:



reflect(x, y) | Inherited from x - 2.0 * dot(x, y) * y
-- | --

So, assuming everything is finite,  some easy problematic cases are:
 
abs(x) > 1 and abs(y) > sqrt(f32.max)   because then last term blows up

abs(x) = f32.max    abs(y) >= 1.   the 2.0 factor makes it blow up.


The others are way less interesting, IMHO

**Comment by dj2** [comment]
Another interesting one is, if you did the calculation in `f64` where the internal calculation is greater then `f32` but the result is within `f32` range should fail.

**Comment by ben-clayton** [comment]
So the part I'm not sure we can test is `or intermediaries go OOB`. This requires a precisely-defined implementation, which I'm not sure the specification gives. It's my understanding that `reflect<f16>` is free to work with higher precision before outputting the value as the spec-defined result?

**Comment by dneto0** [comment]
Ah, I get it.   You're right.
Only the *accuracy* needs to be inherited from.  Not the implementation.  Interesting.

**Comment by zoddicus** [comment]
https://github.com/gpuweb/cts/blob/main/src/webgpu/shader/validation/expression/call/builtin/reflect.spec.ts
