### ISSUE TITLE
Investigate handling of very small (near zero) AbstractFloats and ECMAScript `numbers`

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#2993]
There exists a fundamental issue in the CTS numerics framework around the fact there is an assumption that the native format of numerics is always higher precision then the operations being tested in the CTS.

For f16 and f32 things are fine, because `number` is a f64 under the hood. We run into issues when dealing AbstractFloats, since they are f64s also.

Most of the time this isn't an issue, expect for when dealing with subnormals.
Specifically if a infinitely precise result is calculated such that it is near 0, but not exactly 0, and closer to 0 than the nearest f64 subnormal, the testing framework will treat it like it is precisely 0.

For example:
`y = f64.positive.subnormal.max * f64.positive.subnormal.max`

y <<< f64.positive.subnormal.min, but also in infinite precision y =/= 0.
Thus the correct interval is [0, f64.positive.subnormal.min], but the testing framework will loose precision and return an interval of [0].

This could be resolved by using an underlying numeric that is higher precision, i.e. f128, but that is not spec'd as a part of ECMAScript, so would require a third_party dependency (or custom implementation), and most systems that these tests are running on do not have 128-bit FP hardware instructions, so I would expect these operations to be order of magnitudes slower.

Given the lack of prevalence of 128-bit FP in the wild, it is unlikely real world devices will hit this issue, i.e. returning f64.positive.subnormal.min instead of 0, unless they have drastically different implementations of the builtins (my example was for multiplication, but in theory this issue could crop up anywhere, like a trigonometric function, which there tends to be more implementation diversity.)

So this issue is for
a) being a reference for this high-level issue that I can point in comments when I know I am doing something that expresses it (i.e. the fma unit tests),
b) be a place to track if this issue is actually seen in the wild,
c) a work item for investigating if it is feasible to patch over this in the framework (i.e. have the abstract multiplication interval implementation check for non-zero inputs that return 0)

**Comment by zoddicus** [comment]
FYI @ben-clayton @dneto0 @jzm-intel

**Comment by jzm-intel** [comment]
The tricky thing is, I am afraid that lack of higher precision for abstract-float computation is effecting the `correctly rounded` expectation intervals not only in the near-zero situation. For example, consider the multiple interval `*`, which is expected to be `correctly rounded` i.e. rounded to either value for a ground truth result that falls between them. So, `f64(0.1) * f64(0.1)` falls between and should be rounded to `0x3F847AE147AE147B` and `0x3F847AE147AE147C`, but currently we only expect a single `0x3F847AE147AE147C`. On the other hand, `f32` and `f16` correctly expect the `correctly rounded` interval.

On the other hand, currently all the abstract float execution tests pass, suggesting that tested implementation compute the abstract float or f64 in the same way CTS compute the expectation intervals.

**Comment by jzm-intel** [comment]
Just a note, accuracy requirement of abstract float expression depends on the requirement of f32, af `correct result` for f32 `correct result`, af `correctly rounded` for f32 `correctly round`, and [af `unbounded but at most the error of f32 in absolute terms` otherwise](https://gpuweb.github.io/gpuweb/wgsl/#i32-builtin:~:text=However%2C%20the%20error%20of%20the%20AbstractFloat%20operation%20should%20be%20at%20most%20the%20error%20of%20the%20corresponding%20operation%20in%20f32%2C%20in%20absolute%20terms.).

**Comment by zoddicus** [comment]
Had a chat with dneto about this offline, since I was slightly confused from reading the spec again.

For exact and correctly rounded accuracies, AF should calculate things as an f64.
For other errors, i.e. ULP and absolute, technically for AF they are unbounded, but we should test that they are at least as good as f32.

So I think there isn't anything that needs to be done for correctly rounded tests, but I need to go in and change the behaviour for the AF trait for ULP and absolute error before implementing those tests.

**Comment by jzm-intel** [comment]
The [spec 14.6.2](https://gpuweb.github.io/gpuweb/wgsl/#concrete-float-accuracy:~:text=Let%20x%20be%20the%20exact%20real%2Dvalued%20or%20infinite%20result%20of%20an%20operation%20when%20computed%20with%20unbounded%20precision) defines `correctly rounded` result based on `the exact real-valued or infinite result of an operation when computed with unbounded precision`, and round it to both side in target FP type `T` if the exact result is not exactly-representable in `T`.

So I thought for the af (i.e. f64) cases, correctly-rounded result may still possibly an interval, which currently will not happen in the implementation of e.g. multiplication op.

Take the case `f64(0.1)*f64(0.1)` as example, `f64(0.1) = 0x3FB999999999999A = 0x19_9999_9999_999An * 2 ** -56`, by computing in infinite accuracy the result should be `0x28f5c28f5c28f70a3d70a3d70a4n * 2 ** -112`, which is not exactly representable in f64. To round the result to f64, split the integer part to leading 1, 52 MSB bits after the leading 1 (i.e. the mantissa bits of f64), and the rest. The mantissa bits would be `0x4_7AE1_47AE_147Bn`, and since the remain part is larger than zero, the result could also have mantissa bits `0x4_7AE1_47AE_147Cn`. Together with the sign bit and the exponent bits, the f64 correctly rounded result should be `0x3F84_7AE1_47AE_147B` and `0x3F84_7AE1_47AE_147C`, i.e. `f64(0.01)` and `f64(0.01) + 1ULP`. But currently we only expect a single `0x3F847AE147AE147C` i.e. `f64(0.01) + 1ULP`.

**Comment by jzm-intel** [comment]
Also cc @dneto0

**Comment by jzm-intel** [comment]
Thanks for the clarification!

**Comment by zoddicus** [comment]
note for future reference:
potential high-precision library to use, https://github.com/MikeMcl/decimal.js/.
Supports most of the common math functions, so wouldn't require implementing a bunch of math ourselves with a relatively fluent API.

**Comment by zoddicus** [comment]
Spent a bit of time experimenting with decimal.js. It is possible to rework correctlyRoundedF64 to use it, and handle these cases correctly. The complication is that it would have to be propagated out to floating_point.ts to be useful, since we would need the higher precision other places, otherwise we are just doing high precision math on things that have been quantized to f64.

I can see three-ish paths forward if we wanted to pursue this.
1. Just whole cloth replace usage of number with Decimal. This would be the simplest from an implementation stand point, but we would be converting 'fast' native numbers over to 'slow' Decimals in a bunch of places where it is isn't needed (f32 and f16), so this would cause the CTS to be even slower than it already it is
2. Fork AbstractFloat off, and only replace its usage of number with Decimal. This helps with the performance hit, but this is going to be a maintenance nightmare as fixes/changes in one stack need to be propagated to the other to keep the code from diverging.
3. Create some sort of GenericNumber wrapper that can be either a number or a Decimal, and use the appropriate instance for the FP type. This would require reworking the existing code to do things like GenericNumber.add() instead +, since Typescript doesn't have operator overloading. (This type of thing is need with Decimal regardless). This seems like a significant amount of work to get right.

(I am not in favour of introducing a bunch of `| Decimal` all over the code, because that is going to need a bunch of conditional `instanceof Decimal` code, since Decimal and number's APIs are not type compatible.)

In theory math.js, which depends on decimal.js, already has the Number vs BigNumber wrapper with the same API for both things implemented, which would simplify switching between them in the code, but that library contains a bunch of stuff not needed by the CTS, so I am hesitant to pull it in as a dependency.

So, my end conclusion, there are paths forward here if we need to support higher precision math, but they are all costly from an engineering perspective. I am not going to pursue them until we have a clear need for them.

**Comment by zoddicus** [comment]
A significant portion of this issue has been addressed by spec changes that mean for absolute error, ulp error, and inherited error AbstractFloat defers to f32.

The remaining places that need to be addressed is where the expected error is correctly rounded.

After attempting to resolve this via a multiple approaches, I have settled on for the operations of concern using static lookup tables of result in the CTS, since programmticallly calculating the correct intervals in the CTS is particularly different to resolve due to not having native higher precision FP numbers in TS.

I have written a C++ utility for generating the expected values in f128 to determine the rounds.
