### ISSUE TITLE
Add test for GPUCompilationMessage using UTF-16

### ISSUE THREAD

**Issue by stefnotch** [gpuweb/cts#3489]
The specification for https://gpuweb.github.io/gpuweb/#gpucompilationmessage says

> **offset**, of type [unsigned long long](https://webidl.spec.whatwg.org/#idl-unsigned-long-long), readonly
>
>   The offset from the beginning of the shader [code](https://gpuweb.github.io/gpuweb/#dom-gpushadermoduledescriptor-code) in UTF-16 code units to the point or beginning of the substring that [message](https://gpuweb.github.io/gpuweb/#dom-gpucompilationmessage-message) corresponds to.

However, browser implementations tend to use a different encoding for the shader parsers internally. This makes it easy to screw it up when exposing error messages to the frontend, because one has to remember to convert "bytes of UTF-8" (or whatever the internal representation is) to "code units of UTF-16".

This is sadly not just a worry, but an actual problem as evidenced by Firefox's implementation of WebGPU, which will report wrong error message offsets. This is a problem when attempting to build a shadertoy-equivalent for WebGPU.

An easy test case is the following shader. Any parser read the valid comment, and then encounter an invalid token `?`.

`/*🐈🐈🐈🐈🐈🐈🐈*/?`
A correct implementation should return something approximately 19 as the `linePos`.
Meanwhile an implementation that forgot to do the conversion will report approximately 33 as the `linePos`.

I would be willing to contribute a test for this, however I'll need a small bit of guidance to get me started.

**Comment by stefnotch** [comment]
Upstream Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1885238

**Comment by stefnotch** [comment]
Update regarding Chrome's implementation: It's mostly correct, it's just the "unhandled error handler" that reports wrong columns in the text. The actual `GPUCompilationInfo` struct has correct data.


![image](https://github.com/gpuweb/cts/assets/10220080/a10eaf7b-4f1b-41b1-9db9-c7e6b9b70dd0)

**Comment by kainino0x** [comment]
I am surprised this is broken! I thought we had tests for it but... now that I think about it, I don't know where they would be.

Thank you for offering to contribute a test! Please take a look at these docs to get started:
https://github.com/gpuweb/cts/blob/main/docs/intro/README.md

All you should need to do is extend these existing tests:
https://github.com/gpuweb/cts/blob/main/src/webgpu/api/operation/shader_module/compilation_info.spec.ts

Right now, the invalid tests assert which line the error is reported on, but not which offset. Next to `_errorLine` you can put something like `_errorLinePos`, only on the new test case(s). (We don't want to do this for all tests because we don't want to be too prescriptive about exactly where the error is.) Then in the test function, *if* the case defines `_errorLinePos`, check it.

For a test like the one you came up with, I think we can try to test that the offset is exactly correct (I agree it should be 19). Technically the spec does not guarantee the position will be reported exactly, but I think we can give it a try. Please check at least that Chrome, Firefox, and Safari if you can, all report the error in about the same place - even if they count the position wrong. If it needs to be looser, maybe check it's between 18 and 21.

**Comment by kainino0x** [comment]
> Update regarding Chrome's implementation: It's correct, it's just the "unhandled error handler" that reports funny columns in the text. The actual `GPUCompilationInfo` struct has correct data.

Ahh, well, that's good. Though slightly unfortunate because we can't test the indexes in the unhandled error handler are correct. Actually, they shouldn't be in that string at all, according to the suggestion I put in the spec:

> User agents **should not** include detailed compiler error messages or shader text in the message text of validation errors arising here: these details are accessible via getCompilationInfo(). User agents **should** surface human-readable, formatted error details to _developers_ for easier debugging (for example as a warning in the browser developer console, expandable to show full shader source).

but even if we do that the message will still be printed in dev tools. I guess we should fix this - though honestly code unit offsets are not that useful for human readers....
I have filed an issue here: https://crbug.com/329479346

**Comment by stefnotch** [comment]
Happy update:
The Firefox bug is a-gone https://bugzilla.mozilla.org/show_bug.cgi?id=1885238

**Comment by stefnotch** [comment]
Fixed by https://github.com/gpuweb/cts/pull/3513
