### ISSUE TITLE
Clarification on `src/webgpu/listing_meta.json`

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/cts#3522]
With the increase of people working on the WGSL CTS, I have seen a noticeable uptick in people tripping over needing to add entries to  `src/webgpu/listing_meta.json` and I am haven't been adequately able explain its neccessity/usage, since I wasn't involved in the design/roll out.

So I have some questions/comments, that hopefully can be answered, and maybe documentation can be updated based on the responses.

My understanding is that this file is a meant to a be a set of estimates of the time taken to run tests, to assist in load balancing of execution shards. (But to my knowledge no one is currently using it).
- Is this actively being used at the moment? i.e. is there any implementors of WebGPU that use this information as part of their their CI, etc.
- If not, is it being actively worked on as a near term project?
- If it is not, should not having these entries be a blocking error for commits or even a warning for zeroes?

There is some concerns about methodology, because there doesn't appear to be a common baseline implementation/machine being used.
Specifically people have called out that they are generating values orders of magnitude different from what is in the file, which may be partially due to issues in dawn.node. But I am not aware of any mitigation of the situation of person a) generates some values on a slower CPU based run  and person b) generates others on a fast modern GPU. (This is could also be compounded by node vs browser based timing or using different WebGPU implementations.)

The concern here is that it is unclear that using these values for load balancing decisions would be any better then something like just round-robining down the list of tests to run, since though the cost values are in the same units (mS), there is no way to know if they are comareable.
- Is there a doc or something that discusses this?

The final concern I have heard is about the location of this timing data.
- As mentioned above, it appears to be pretty tightly coupled to the machine and environment that the tests are executed on, so is in the the general CTS tree the proper location? 

- Having the common load balancing logic live in CTS repo seems sensible, but should the specific values be provided by the different implementations of WebGPU as part of their CI, since it is unlikley one set of values would apply to all implementations?

(This could be somewhat mitigated if the values were all calculated by a common baseline machine, so aleast they could be considered be relative costs, but that would not address if different implementations have significantly different runtimes between, i.e. test A is faster than test B on one implementation but reversed on another)

**Comment by zoddicus** [comment]
FYI @dneto0 @ben-clayton

**Comment by kainino0x** [comment]
> * Is this actively being used at the moment? i.e. is there any implementors of WebGPU that use this information as part of their their CI, etc.
> * If not, is it being actively worked on as a near term project?

This is a good question and I don't know the answer. IIRC WebKit wanted to use it and Mozilla didn't need it...? But I can't find the thread or email where we talked about it.

@mwyrzykowski @jimblandy ?

> The concern here is that it is unclear that using these values for load balancing decisions would be any better then something like just round-robining down the list of tests to run, since though the cost values are in the same units (mS), there is no way to know if they are comareable.

It's not intended for round-robining (sorry this is completely unclear). It's to keep chunk times under the fixed timeout threshold of WPT (chunk = WPT variant = 1 page load = some subtree of test cases).

For this reason it's OK if the numbers are overestimates. That just causes the test suite to be chunked more finely and take a bit longer to run. And if it is found that some test machine runs a test slower than estimated and a timeout occurs, then that test's estimate should be increased.

One thing that I didn't discover until after I decided to do this project was that it doesn't actually take that long to run all the tests to capture the estimates. We could maybe make downstream importers do this as part of their roll process if they need it.

Another idea if we need to keep these is to actually run the tests on some real device periodically and have that update the estimates instead of making test developers do it.

**Comment by dneto0** [comment]
The discussion covers a lot of good points.

Some points:
* the data is necessarily an estimate
* the estimate can be way off and still useful
* it's unlikley a single device will cover all functionality due to future extensions

I would favour taking this data out of this repo.
But have tooling that can (1) generate case listings, and (2) generate the timing estimate data.

Downstream consumers can generate the data relevant to their case.  That should feed into their own scheduling system, and I hope that scheduling system would tolerate addition and subtraction of cases, or cases with invalid or 0-time estimates.

**Comment by mwyrzykowski** [comment]
> This is a good question and I don't know the answer. IIRC WebKit wanted to use it and Mozilla didn't need it...? But I can't find the thread or email where we talked about it.
> 
> @mwyrzykowski @jimblandy ?
> 

We are not importing listing_meta.json into our cached copy of the CTS, so we certainly do not need it

**Comment by kainino0x** [comment]
> We are not importing listing_meta.json into our cached copy of the CTS, so we certainly do not need it

You don't necessarily need to be importing that file. It's used at `out-wpt` build time, generating [`cts-chunked2sec.https.html`](https://github.com/gpuweb/cts/blob/gh-pages/out-wpt/cts-chunked2sec.https.html) by default for example (but can also be used to generate other chunk sizes by configuring the generator).

It's supposed to help avoid WPT per-variant time limits (IIRC in WebKit you also have to split the variants list out into a big list, but you can still use the list it generates).

**Comment by kainino0x** [comment]
I'll go ahead and remove the blocking and warnings, as everything works fine when there's missing metadata. Anytime it's found that the metadata needs an update for better chunking, we can update it.

**Comment by kainino0x** [comment]
https://github.com/gpuweb/cts/pull/3548

> **Note: `listing_meta.json` is no longer an exhaustive list of tests. Use `gen/webgpu_variant_list.json` if you need this.**
