### ISSUE TITLE
Create*PipelineAsync on lost device

### ISSUE THREAD

**Issue by sagudev** [gpuweb/cts#3867]
CTS expects that Create*PipelineAsync should succeed even on lost device: https://github.com/gpuweb/cts/blob/20425f60bb00676af386b5c31e7748c0e2cb1702/src/webgpu/api/validation/state/device_lost/destroy.spec.ts#L526-L530

but specs says that device is invalidated on destroy: https://www.w3.org/TR/webgpu/#dom-gpudevice-destroy and https://www.w3.org/TR/webgpu/#lose-the-device, but when doing https://www.w3.org/TR/webgpu/#dom-gpudevice-createcomputepipelineasync more specifically 
> 1. https://www.w3.org/TR/webgpu/#dom-gpudevice-createcomputepipeline layout must be [valid to use with](https://www.w3.org/TR/webgpu/#abstract-opdef-valid-to-use-with) this.

and [valid to use with](https://www.w3.org/TR/webgpu/#abstract-opdef-valid-to-use-with) specifies:

> object.[[[device]]](https://www.w3.org/TR/webgpu/#dom-gpuobjectbase-device-slot).[[[valid]]](https://www.w3.org/TR/webgpu/#dom-gpuobjectbase-valid-slot) must be true.

so createComputePipeline produces validation error and this should map to rejection of createComputePipelineAsync, right?

**Comment by kainino0x** [comment]
Oh, good catch. This is a bug in the spec - per https://github.com/gpuweb/gpuweb/issues/1629, we want to pretend that pipeline creation succeeds when the device is lost. I completely forgot about this problem, but it turns out we actually discussed it a year ago. And it so happens that I just opened a spec PR which fixes this. It does so by checking at the last moment whether the device is lost, and if so, resolving the promise as if the operation was successful.

 https://github.com/gpuweb/gpuweb/pull/4752#issuecomment-2229864542
