### ISSUE TITLE
Add new formats to capability_info

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#467]
_Originally posted by @Richard-Yunchao in https://github.com/gpuweb/cts/pull/455#discussion_r579424106_

I noticed that a few texture formats are missing in CTS and Dawn, compared to spec.
The texture formats we are missing in CTS (src/webgpu/capability_info.ts): depth16unorm, depth24unorm-stencil8, depth32float-stencil8
The texture formats we are missing in Dawn (dawn.json): stencil8 + all missing formats in CTS.

**Comment by kainino0x** [comment]
We should add them to capability_info. Unfortunately adding items to capability_info is quite disruptive as it usually results in a lot of tests getting expanded, and sometimes breaking. In this case we might be okay, but we should try to make sure we fix tests immediately (we forgot to do this last time and ended up with a bunch of broken test cases).

**Comment by Richard-Yunchao** [comment]
Got it. I will add the missing formats. 

Recently I am adding tests to createTexture and createView. These two tests should add a lot of tests for texture and exhaust every single formats (another heavy user of various texture formats is copy). So I think it is good to add the missing formats before I add more tests for createTexture and createView. Otherwise, we may break more tests when we add the missing texture formats in future.

**Comment by kainino0x** [comment]
SGTM

**Comment by Richard-Yunchao** [comment]
I suppose this issue is fixed now, although it is possible that we may miss some trivial fixes somewhere.

**Comment by kainino0x** [comment]
That's okay, we'll find those issues later. Thanks for working on this!
