### ISSUE TITLE
Adding wgsl validation folder in CTS automatically

### ISSUE THREAD

**Issue by munrocket** [gpuweb/cts#674]
Currently wgsl [almoust not tested](https://gpuweb.github.io/cts/standalone/?runnow=0&worker=0&debug=0&q=webgpu:shader,validation,wgsl,basic:*) by current CTS implementation

Is there any plans for adding shaders that existed in [validation folder](https://github.com/gpuweb/cts/tree/main/src/webgpu/shader/validation/wgsl) automatically? With names/erros/codes.

**Comment by kainino0x** [comment]
We had planned to find a way to import them but right now they just exist as a corpus that can be imported manually.

Eventually, instead, I think we will move them into embedded strings in `.spec.ts` files, like the few automated WGSL tests we do have now.

Right now the Tint team (at Google) has not been focusing on adding CTS tests for WGSL, because our development process for changing tests and implementation is extremely arduous. It is something we will work on soon (after we branch for our Origin Trial) so that the team can work on expanding out the testing (and porting tests from Tint and Dawn into the CTS).

**Comment by munrocket** [comment]
Roughly speaking your plan is to copy tests from dawn and naga when WGSL will be little bit more stable and automatically generate `.spec.ts` from it.

I just found that Firefox and Chrome already have a subset of WGSL that works in both of browsers. And expected to find some tests here 😅 But you working on testing independently for now.

**Comment by kainino0x** [comment]
Not automatically, but yes. Yeah, it's unfortunate that the testing is independent right now. It will be much easier to share test cases when the language stabilizes. (As we found with WebGPU, otherwise the browsers advance through different paths, so often tests will just not pass in both until they both advance far enough.)

**Comment by munrocket** [comment]
This was just a question, so can be closed.
